// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.26.1
// source: membership.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MembershipService_ApplyMembership_FullMethodName  = "/membership.MembershipService/ApplyMembership"
	MembershipService_CopyPeers_FullMethodName        = "/membership.MembershipService/CopyPeers"
	MembershipService_CancelMembership_FullMethodName = "/membership.MembershipService/CancelMembership"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipServiceClient interface {
	ApplyMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	CopyPeers(ctx context.Context, in *CopyPeersRequest, opts ...grpc.CallOption) (*CopyPeersResponse, error)
	CancelMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) ApplyMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_ApplyMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CopyPeers(ctx context.Context, in *CopyPeersRequest, opts ...grpc.CallOption) (*CopyPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyPeersResponse)
	err := c.cc.Invoke(ctx, MembershipService_CopyPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CancelMembership(ctx context.Context, in *MembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_CancelMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility
type MembershipServiceServer interface {
	ApplyMembership(context.Context, *MembershipRequest) (*MembershipResponse, error)
	CopyPeers(context.Context, *CopyPeersRequest) (*CopyPeersResponse, error)
	CancelMembership(context.Context, *MembershipRequest) (*MembershipResponse, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMembershipServiceServer struct {
}

func (UnimplementedMembershipServiceServer) ApplyMembership(context.Context, *MembershipRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyMembership not implemented")
}
func (UnimplementedMembershipServiceServer) CopyPeers(context.Context, *CopyPeersRequest) (*CopyPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyPeers not implemented")
}
func (UnimplementedMembershipServiceServer) CancelMembership(context.Context, *MembershipRequest) (*MembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMembership not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_ApplyMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ApplyMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ApplyMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ApplyMembership(ctx, req.(*MembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CopyPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CopyPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CopyPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CopyPeers(ctx, req.(*CopyPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CancelMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CancelMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CancelMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CancelMembership(ctx, req.(*MembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membership.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyMembership",
			Handler:    _MembershipService_ApplyMembership_Handler,
		},
		{
			MethodName: "CopyPeers",
			Handler:    _MembershipService_CopyPeers_Handler,
		},
		{
			MethodName: "CancelMembership",
			Handler:    _MembershipService_CancelMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership.proto",
}
